FROM maven:3.9.8-eclipse-temurin-21

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

EXPOSE 8080

CMD ["java","-jar","target/backend-0.0.1-SNAPSHOT.jar"]






# FROM eclipse-temurin:21-jdk

# WORKDIR /app

# COPY . .

# RUN chmod +x mvnw

# RUN ./mvnw clean package -DskipTests

# EXPOSE 8080

# CMD ["java","-jar","target/backend-0.0.1-SNAPSHOT.jar"]