spring.application.name=backend
# groq.api.key=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
groq.api.key=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

server.port=${PORT:8080}
